name: CACI CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'caci/package-lock.json'

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-nodemodules
        with:
          path: |
            caci/node_modules
            ~/.cache/npm
            ~/.npm
            %APPDATA%/npm-cache
            %LOCALAPPDATA%/npm-cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('caci/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        working-directory: caci
        run: npm ci

      - name: Build project
        working-directory: caci
        run: npm run build

      - name: Run tests
        working-directory: caci
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm test

      - name: Run tests with coverage
        working-directory: caci
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run test:coverage

      - name: Test flakiness detection (run tests multiple times)
        working-directory: caci
        shell: bash
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          echo "Running tests multiple times to detect flakiness..."
          for i in 1 2 3; do
            echo "Test run $i"
            npm test || exit 1
          done

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20'
        uses: codecov/codecov-action@v4
        with:
          file: ./caci/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: caci/coverage/
          retention-days: 30

      - name: Test CLI installation and basic commands
        shell: bash
        working-directory: caci
        run: |
          npm pack
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # On Windows, use npm link instead of global install for testing
            npm link
            npx caci --help || true
            npx caci --version || true
          else
            npm install -g caci-*.tgz
            caci --help || true
            caci --version || true
          fi

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'caci/package-lock.json'

      - name: Install dependencies
        working-directory: caci
        run: npm ci

      - name: Build for production
        working-directory: caci
        run: npm run build

      - name: Check build artifacts
        working-directory: caci
        run: |
          ls -la dist/
          test -f dist/cli/index.js
          test -f dist/cli/index.js.map
          test -f dist/cli/index.d.ts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: caci/dist/
          retention-days: 7

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'caci/package-lock.json'

      - name: Install dependencies
        working-directory: caci
        run: npm ci

      - name: Build project
        working-directory: caci
        run: npm run build

      - name: Run integration tests
        working-directory: caci
        run: |
          if [ -d "tests/integration" ]; then
            npm test -- --testPathPattern=integration
          else
            echo "No integration tests found, skipping..."
          fi

      - name: Test with real components.json files
        working-directory: caci
        run: |
          # Create test scenarios
          mkdir -p test-scenarios
          
          # Test with existing test workspace
          if [ -f "test-workspace/components.json" ]; then
            echo "Testing with existing components.json..."
            cd test-workspace
            node ../dist/cli/index.js --help || true
            cd ..
          fi

  notify:
    name: Notify on failure
    runs-on: ubuntu-latest
    needs: [test, build-test, integration-test]
    if: failure()
    
    steps:
      - name: Notify failure
        run: |
          echo "CI Pipeline failed. Check the logs for details."
          echo "Failed jobs: ${{ toJSON(needs) }}"