name: Debug Repository Structure

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug Structure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check repository structure
        run: |
          echo "=== Repository Root ==="
          ls -la
          echo ""
          echo "=== packages/ directory ==="
          ls -la packages/
          echo ""
          echo "=== packages/caci/ directory ==="
          ls -la packages/caci/
          echo ""
          echo "=== Check for package-lock.json ==="
          echo "packages/caci/package-lock.json exists: $(test -f packages/caci/package-lock.json && echo 'YES' || echo 'NO')"
          echo ""
          echo "=== Working directory test ==="
          cd packages/caci
          echo "Current directory: $(pwd)"
          echo "Contents:"
          ls -la
          echo "package-lock.json exists here: $(test -f package-lock.json && echo 'YES' || echo 'NO')"