name: 'Test NPM CI Debug'

on:
  workflow_dispatch:

jobs:
  debug-npm-ci:
    name: 'Debug NPM CI'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - Show current directory structure
        run: |
          echo "=== Current directory ==="
          pwd
          ls -la
          echo "=== packages/caci directory ==="
          ls -la packages/caci/
          echo "=== Test package-lock.json ==="
          cat packages/caci/package-lock.json | head -10

      - name: Setup Node.js with correct cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/caci/package-lock.json'

      - name: Debug - Test NPM CI in packages/caci
        run: |
          echo "=== Working directory before cd ==="
          pwd
          ls -la
          cd packages/caci
          echo "=== Working directory after cd ==="
          pwd
          ls -la
          echo "=== Test package.json ==="
          cat package.json | head -10
          echo "=== Test package-lock.json ==="
          ls -la package-lock.json
          echo "=== Check package-lock.json content ==="
          head -20 package-lock.json
          echo "=== Check lockfileVersion ==="
          grep -A 2 -B 2 "lockfileVersion" package-lock.json || echo "No lockfileVersion found!"
          echo "=== Try NPM CI ==="
          npm ci
        shell: bash

      - name: Success summary
        run: |
          echo "✅ NPM CI worked successfully!" >> $GITHUB_STEP_SUMMARY