name: Test Called Workflow

on:
  workflow_call:
    inputs:
      test_input:
        description: 'Test input'
        required: true
        type: string
    outputs:
      test_output:
        description: 'Test output'
        value: ${{ jobs.test-job.outputs.result }}

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.test.outputs.value }}
    
    steps:
      - name: Test step
        id: test
        run: |
          echo "Received input: ${{ inputs.test_input }}"
          echo "value=success-${{ inputs.test_input }}" >> $GITHUB_OUTPUT