name: Test Validation

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message'
        required: false
        default: 'Hello World'
        type: string

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Test step
        run: |
          echo "✅ Test successful: ${{ inputs.test_message }}"
          echo "✅ All workflow syntax is valid"