name: 'Test Simple Workflow Call'

on:
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Test version'
        required: false
        default: 'v1.0.0'
        type: string

jobs:
  test-call:
    name: 'Test Call NPM Workflow'
    runs-on: ubuntu-latest
    
    steps:
      - name: Test step
        run: echo "Testing workflow call with version ${{ inputs.test_version }}"

  call-npm:
    name: 'Call NPM Workflow'
    needs: test-call
    uses: ./.github/workflows/publish-npm.yml
    with:
      version: ${{ inputs.test_version }}
      dry_run: true
    secrets: inherit