name: Test Call NPM Minimal

on:
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Test version'
        required: false
        default: 'v1.0.2'
        type: string

jobs:
  test-npm-minimal-call:
    name: Test NPM Minimal Call
    uses: ./.github/workflows/test-npm-minimal.yml@master
    with:
      version: ${{ inputs.test_version }}
      dry_run: true
    secrets: inherit

  summary:
    name: Summary  
    needs: test-npm-minimal-call
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Show results
        run: |
          echo "NPM minimal workflow result: ${{ needs.test-npm-minimal-call.result }}"
          echo "## NPM Minimal Workflow Call Test" >> $GITHUB_STEP_SUMMARY
          echo "- Input version: ${{ inputs.test_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- NPM call result: ${{ needs.test-npm-minimal-call.result }}" >> $GITHUB_STEP_SUMMARY