name: 'Test Minimal Release'

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: 'Dry run (no actual release)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  test-prepare:
    name: 'Test Prepare'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test working directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Packages directory:"
          ls -la packages/
          echo "CACI directory:"
          ls -la packages/caci/

      - name: Test Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/caci/package-lock.json'

      - name: Test installation
        run: npm install
        working-directory: packages/caci

      - name: Test version check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
        working-directory: packages/caci

      - name: Summary
        run: |
          echo "✅ Basic workflow test successful" >> $GITHUB_STEP_SUMMARY
          echo "- Directory structure: OK" >> $GITHUB_STEP_SUMMARY  
          echo "- Node.js setup: OK" >> $GITHUB_STEP_SUMMARY
          echo "- NPM install: OK" >> $GITHUB_STEP_SUMMARY
          echo "- Version check: OK" >> $GITHUB_STEP_SUMMARY
