name: 'Test Prepare Release Only'

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: 'Dry run (no actual release)'
        required: false
        default: false
        type: boolean

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: --max-old-space-size=4096

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  prepare-release:
    name: 'Prepare Release'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      version: ${{ steps.version_bump.outputs.new }}
      current_version: ${{ steps.current_version.outputs.current }}
      should_release: ${{ steps.version_bump.outputs.should_release }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/caci/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: packages/caci

      - name: Run all tests
        run: npm test
        working-directory: packages/caci

      - name: Build package
        run: npm run build
        working-directory: packages/caci

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        working-directory: packages/caci

      - name: Bump version
        id: version_bump
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "🔍 DRY RUN MODE - No actual version bump"
            # Get current version and calculate what the new version would be
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            NEW_VERSION=$(node -e "
              const semver = require('semver');
              const current = '$CURRENT_VERSION';
              const bump = '${{ inputs.version_bump }}';
              console.log('v' + semver.inc(current, bump));
            ")
            echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "📦 Bumping version: ${{ inputs.version_bump }}"
            NEW_VERSION=$(npm version ${{ inputs.version_bump }} --no-git-tag-version)
            echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi
        working-directory: packages/caci

      - name: Create test artifacts
        run: |
          echo "📦 Creating test artifacts..."
          npm pack
        working-directory: packages/caci

      - name: Summary
        run: |
          echo "## 🔍 Prepare Release Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Node.js Setup | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          echo "| Dependencies | ✅ Installed |" >> $GITHUB_STEP_SUMMARY
          echo "| Tests | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          echo "| Version Check | ✅ ${{ steps.current_version.outputs.current }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version Bump | ✅ ${{ steps.version_bump.outputs.new }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Should Release | ${{ steps.version_bump.outputs.should_release }} |" >> $GITHUB_STEP_SUMMARY
